version: '3.8'

services:
  ai-aesthetic-scorer:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped 